# Generated by Django 4.2.6 on 2023-12-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_blog_blog_body_alter_blog_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
