# Generated by Django 4.2.6 on 2023-12-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0005_alter_blog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
