# Generated by Django 4.2.6 on 2023-12-31 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0006_blog_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="created_at",
        ),
    ]
